### ISSUE TITLE
Please compile a wheel with python3.6

### ISSUE THREAD

**Issue by Xtscat** [rockman4308/MC2_gesture_detection_pynqz2_tensorflow#1]
Hi, my board is zynq7020 and use pynq image on it.
But the default python version is python3.6
I have tried compile tensorflow with python3.6 for a week but never succeed, so can you give me a compiled wheel with python3.6?
thanks.

**Comment by rockman4308** [comment]
Sorry about that we try to compile  tensorflow with python3.6 at first  , but we never success too.
